### ISSUE TITLE
BUG:IndexError: list index out of range (process_ROIs-savename = process.run)

### ISSUE THREAD

**Issue by liwei4932** [MouseLand/facemap#127] opened 2023-10-09 12:30 UTC
### Version information:

facemap version:1.0.4
platform: win32
python version:3.8.18
torch version:2.1.0+cpu
numpy version:1.24.4

### Describe the issue:

When I try running python -m facemap I receive the following error.

Computing subsampled mean...
Computed subsampled mean at 10.42s
Computing subsampled SVD...
computed svd chunk 0 / 3, time  5.73sec
computed svd chunk 1 / 3, time  12.10sec
computed svd chunk 2 / 3, time  18.60sec
Computed subsampled SVD at 30.09s
  File "C:\Users\ASUS\.conda\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 1300, in process_ROIs
    savename = process.run(
  File "C:\Users\ASUS\.conda\envs\facemap\lib\site-packages\facemap\process.py", line 806, in run
    U_mov[k].copy(), (ly, lx, U_mov[k].shape[-1])
IndexError: list index out of range

**Comment by liwei4932** [comment] 2023-10-09 12:33
when I process mot/movSVD

**Comment by inchinn1** [comment] 2023-10-11 09:06
I have the same issue...

**Comment by JohannesCD** [comment] 2023-10-23 14:29
same here

**Comment by Atika-Syeda** [comment] 2023-10-26 19:40
Hi @magdalenasabat could you please try reinstalling facemap and creating a new virtual environment. The output of pip list shows you have pyqt5 and pyqt6 while we're only using pyqt6 so just to eliminate that as the issue.

**Comment by Atika-Syeda** [comment] 2023-10-26 19:43
Hi @liwei4932 @inchinn1 @JohannesCD could you please provide more details so I can try to reproduce the error. It's working fine when I tested with the new version. More details about the video loaded and the steps that lead to the error would be great. If you updated to the new version then I'd suggest creating a new virtual env.

**Comment by magdalenasabat** [comment] 2023-10-27 08:42
Hi! PyQT5 is part of spyder installation. Everything is working well now. In my case the cv2 was reading in incorrect number of frames. I know that somewhere burried in the metadata my videos have wrong framerate (600), even though cv2 is reading in the correct frame rate (10) the total number of frames seems to be calculated with the wring framerate (exactly 600 times more than there should be). So correcting the property cv2.CAP_PROP_POS_FRAMES fixes the issue and everything works bueno.

**Comment by karansingh102** [comment] 2023-11-10 23:19
> Hi! PyQT5 is part of spyder installation. Everything is working well now. In my case the cv2 was reading in incorrect number of frames. I know that somewhere burried in the metadata my videos have wrong framerate (600), even though cv2 is reading in the correct frame rate (10) the total number of frames seems to be calculated with the wring framerate (exactly 600 times more than there should be). So correcting the property cv2.CAP_PROP_POS_FRAMES fixes the issue and everything works bueno.

I have the same issue. What do you mean by

**Comment by karansingh102** [comment] 2023-11-10 23:19
> Hi! PyQT5 is part of spyder installation. Everything is working well now. In my case the cv2 was reading in incorrect number of frames. I know that somewhere burried in the metadata my videos have wrong framerate (600), even though cv2 is reading in the correct frame rate (10) the total number of frames seems to be calculated with the wring framerate (exactly 600 times more than there should be). So correcting the property cv2.CAP_PROP_POS_FRAMES fixes the issue and everything works bueno.

I have the same issue. What do you mean by cv2. Is this the object in the metadata?

**Comment by JohannesCD** [comment] 2023-11-20 13:06
Hi @Atika-Syeda, thanks for looking into this. The error seems independent of the particular video that I try to process. I tried some of mine but the same error also comes up when using 'mouse_face.mp4' from the list of provided example videos (https://drive.google.com/drive/folders/1cRWCDl8jxWToz50dCX1Op-dHcAC-ttto). All I have done was to load the video into the GUI and click 'process' with 'motSVD', 'Save *.mat' and 'multivideo' checked.     

facemap version:        1.0.4
platform:               win32
python version:         3.8.18
torch version:          2.1.0+cpu
numpy version:          1.24.4

** Using CPU version. **
TORCH CUDA version not installed/working. Using CPU version.
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
Computing subsampled mean...
Computed subsampled mean at 1.82s
Computing subsampled SVD...
computed svd chunk 0 / 1, time  1.32sec
Computed subsampled SVD at 3.69s
Traceback (most recent call last):
  File "C:\Users\jd\.conda\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 1300, in process_ROIs
    savename = process.run(
  File "C:\Users\jd\.conda\envs\facemap\lib\site-packages\facemap\process.py", line 794, in run
    U_mov_reshape[0], LYbin, LXbin, sybin, sxbin, Lybin, Lxbin, iinds
IndexError: list index out of range
QGraphicsScene::removeItem: item 0x2adb9dcd3c0's scene (0x0) is different from this scene (0x2ad8e847ae0)
Computing subsampled mean...
Computed subsampled mean at 3.66s
Computing subsampled SVD...
computed svd chunk 0 / 5, time  2.17sec
computed svd chunk 1 / 5, time  4.71sec
computed svd chunk 2 / 5, time  7.30sec
computed svd chunk 3 / 5, time  9.88sec
computed svd chunk 4 / 5, time  12.67sec
Computed subsampled SVD at 17.32s
Traceback (most recent call last):
  File "C:\Users\jd\.conda\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 1300, in process_ROIs
    savename = process.run(
  File "C:\Users\jd\.conda\envs\facemap\lib\site-packages\facemap\process.py", line 794, in run
    U_mov_reshape[0], LYbin, LXbin, sybin, sxbin, Lybin, Lxbin, iinds
IndexError: list index out of range

**Comment by Atika-Syeda** [comment] 2023-11-21 22:13
Hi @JohannesCD thanks for testing it. We've found the bug and it should be fixed in the new release (v1.0.6). Could you please install the latest pip version (v1.0.6) and let us know if the issue still persists.

**Closed** 2023-11-27 14:52 UTC

**Comment by phanhuynh** [comment] 2024-03-18 13:05
Hello!  I believe I'm having the same issues; it started when I added a second and third 'motion SVD' ROI.  
I already have v1.0.6.
